server:
  port: 8080
  address: localhost
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{HH:mm:ss}){white} %clr(%level){green}: %msg%n"

spring:
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration